name = "1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ed9a52cfa9f2d94b4549454fa47bfe91150c6f6a6d4d8fde044418b9c5ca55"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
