name = "1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5a5196c9205603f2af4faa3c46499a74330b1ad97cff697f4c7cb3cc5b35ac7"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
