name = "1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba4b434955c84889113a8b203c7e28f4cb9383f95d92b9a6685bb8dbaa6beab6"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
