name = "1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eddefd16af72d6d4a8f50aee254c75a907a96feff81554b84b02d4a8b6a8403"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
