name = "1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "241f3ced4eedaf60011b7caa624d195f36b7bdef9de9c85d8d091fbf4b08db69"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
