name = "1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79ec8ebf6dd38266a3d1c0a44ca6c58c2a57a9c97cb1adc4954605fde7155344"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
